# official python image
image: python:3-alpine

variables:
  GIT_DEPTH: "1"

stages:
  - test

.base-rules:
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    # To make sure it's not creating a detached pipeline on MRs. The branch build is already running then.
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - when: always

test:
  extends: .base-rules
  stage: test
  services:
    - name: $CI_REGISTRY/softwearconnect/local-databases/mongo-e2e
      alias: mongo
  variables:
    MONGODB_URL: "mongo:27017"
  before_script:
    - python3 -m pip install --upgrade pip setuptools wheel pytest pytest-cov
    - python3 -m pip install -e .
  script:
    - py.test --junit-xml=report.xml --cov=spynl_schemas --cov=spynl_dbaccess tests
    - coverage xml
  artifacts:
    when: always
    expire_in: 2 days
    reports:
      junit: report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml


lint:
  extends: .base-rules
  stage: test
  image: $CI_REGISTRY/softwearconnect/softwear-development/python-linting
  script:
    - flake8 .
    - black -S --check --diff .
    - isort -c .
