#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

export PYTHONSTARTUP=$DIR/mongopy_startup.py

if hash ipython &> /dev/null; then
    ipython
else
    python
fi
